-- 1. Homepage email subscribers
create table if not exists public.innie_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

-- 2. Product and service ratings & feedback
create table if not exists public.innie_product_ratings (
  id bigint generated by default as identity primary key,
  slug text not null,
  rating smallint not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz not null default now()
);

-- Indexes for performance
create index if not exists innie_product_ratings_slug_idx on public.innie_product_ratings (slug);

-- The Vercel API uses the service-role key server-side, so no public insert policy is required.
-- Keep the service-role key out of GitHub and frontend code.

-- 3. One rating per visitor per product (a repeat rating replaces the earlier one).
--    `voter` is a one-way hash of the visitor's IP address; raw IPs are never stored.
alter table public.innie_product_ratings add column if not exists voter text;
create unique index if not exists innie_product_ratings_slug_voter_idx
  on public.innie_product_ratings (slug, voter);

-- 4. Failed admin logins, used to lock out password guessing (5 tries per 15 minutes).
create table if not exists public.innie_admin_login_failures (
  id bigint generated by default as identity primary key,
  visitor text not null,
  created_at timestamptz not null default now()
);
create index if not exists innie_admin_login_failures_visitor_idx
  on public.innie_admin_login_failures (visitor, created_at);

-- 5. Only the server (service-role key) may read or write these tables.
--    With row level security on and no policies, the public anon key gets nothing.
alter table public.innie_subscribers enable row level security;
alter table public.innie_product_ratings enable row level security;
alter table public.innie_admin_login_failures enable row level security;
