-- 1. Homepage email subscribers
create table if not exists public.innie_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

-- 2. Product and service ratings & feedback
create table if not exists public.innie_product_ratings (
  id bigint generated by default as identity primary key,
  slug text not null,
  rating smallint not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz not null default now()
);

-- Indexes for performance
create index if not exists innie_product_ratings_slug_idx on public.innie_product_ratings (slug);

-- The Vercel API uses the service-role key server-side, so no public insert policy is required.
-- Keep the service-role key out of GitHub and frontend code.
