-- INNIE homepage email subscribers
-- Run this once in the Supabase SQL Editor.
create table if not exists public.innie_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

-- The Vercel API uses the service-role key server-side, so no public insert policy is required.
-- Keep the service-role key out of GitHub and frontend code.
